<a href="https://colab.research.google.com/github/Moonrack/uts/blob/main/UTS_Athanasius_Carlos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

path="https://raw.githubusercontent.com/Moonrack/uts/main/loan_data.csv"

In [4]:
df=pd.read_csv(path)
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [5]:
df.duplicated().sum()

0

In [6]:
df.drop(columns=['ApplicantIncome'],inplace=True)
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,1516.0,95.0,360.0,1.0,Urban,Y

In [7]:
df.duplicated().sum()

0

In [8]:
df.isna()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
376,False,False,False,False,False,False,False,False,False,False,False,False
377,False,False,False,False,False,False,False,False,False,False,False,False
378,False,False,False,False,False,False,False,False,False,False,False,False
379,False,False,False,False,False,False,False,False,False,False,False,False
380,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isna().sum()

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [10]:
baris,kolom= df.shape
print(f'Jumlah data ada {baris} record, jumlah fitur ada : {kolom} kolom')

Jumlah data ada 381 record, jumlah fitur ada : 12 kolom

In [11]:
df.drop(columns=['Credit_History'],inplace=True)
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,1508.0,128.0,360.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,0.0,66.0,360.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2358.0,120.0,360.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,0.0,141.0,360.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,1516.0,95.0,360.0,Urban,Y

In [12]:
df.sample(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
51,LP001245,Male,Yes,2,Not Graduate,Yes,1875.0,97.0,360.0,Semiurban,Y
377,LP002974,Male,Yes,0,Graduate,No,1950.0,108.0,360.0,Rural,Y
241,LP002236,Male,Yes,2,Graduate,No,0.0,100.0,360.0,Urban,N
180,LP001926,Male,Yes,0,Graduate,No,2000.0,120.0,360.0,Rural,Y
0,LP001003,Male,Yes,1,Graduate,No,1508.0,128.0,360.0,Rural,N
301,LP002517,Male,Yes,1,Not Graduate,No,1500.0,113.0,180.0,Rural,N
262,LP002332,Male,Yes,0,Not Graduate,No,2033.0,110.0,360.0,Rural,Y
131,LP001720,Male,Yes,3+,Not Graduate,No,983.0,100.0,360.0,Semiurban,Y
194,LP001993,Female,No,0,Graduate,No,1666.0,135.0,360.0,Rural,Y
103,LP001581,Male,Yes,0,Not Graduate,NaN,1769.0,95.0,360.0,Rural,Y

In [13]:
df[df.Self_Employed.isna()]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
6,LP001027,Male,Yes,2,Graduate,NaN,1840.0,109.0,360.0,Urban,Y
13,LP001041,Male,Yes,0,Graduate,NaN,3500.0,115.0,NaN,Urban,Y
20,LP001087,Female,No,2,Graduate,NaN,2083.0,120.0,360.0,Semiurban,Y
72,LP001370,Male,No,0,Not Graduate,NaN,0.0,120.0,360.0,Rural,N
75,LP001387,Female,Yes,0,Graduate,NaN,2333.0,139.0,360.0,Semiurban,Y
76,LP001398,Male,No,0,Graduate,NaN,0.0,118.0,360.0,Semiurban,Y
96,LP001546,Male,No,0,Graduate,NaN,2083.0,120.0,360.0,Rural,Y
103,LP001581,Male,Yes,0,Not Graduate,NaN,1769.0,95.0,360.0,Rural,Y
134,LP001732,Male,Yes,2,Graduate,NaN,0.0,72.0,360.0,Semiurban,N
142,LP001768,Male,Yes,0,Graduate,NaN,0.0,42.0,180.0,Rural,Y
166,LP001883,Female,No,0,Graduate,NaN,0.0,135.0,360.0,Rural,N
186,LP001949,Male,Yes,3+,Graduate,NaN,1250.0,110.0,360.0,Urban,Y
217,LP002128,Male,Yes,2,Graduate,NaN,2330.0,125.0,360.0,Rural,Y
233,LP002209,Female,No,0,Graduate,NaN,1459.0,110.0,360.0,Urban,Y
239,LP002226,Male,Yes,0,Graduate,NaN,2500.0,128.0,360.0,Semiurban,Y
242,LP002237,Male,No,1,Graduate,NaN,0.0,113.0,180.0,Urban,Y
284,LP002435,Male,Yes,0,Graduate,NaN,1376.0,55.0,360.0,Rural,N
295,LP002489,Female,No,1,Not Graduate,NaN,0.0,132.0,360.0,Semiurban,Y
299,LP002502,Female,Yes,2,Not Graduate,NaN,2917.0,98.0,360.0,Semiurban,Y
337,LP002732,Male,No,0,Not Graduate,NaN,2042.0,126.0,360.0,Rural,Y
342,LP002753,Female,No,1,Graduate,NaN,0.0,95.0,360.0,Semiurban,Y

In [14]:
df.LoanAmount.mean()

104.98687664041995

In [15]:
df.LoanAmount.median()

110.0

In [17]:
df.LoanAmount.mode()

0    120.0
Name: LoanAmount, dtype: float64

In [19]:
df.LoanAmount.fillna(df.LoanAmount.mean(), inplace=True)
df.isna().sum()

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Property_Area         0
Loan_Status           0
dtype: int64

In [20]:
df.iloc[[6]]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status
6,LP001027,Male,Yes,2,Graduate,NaN,1840.0,109.0,360.0,Urban,Y

In [21]:
df.Loan_Status.value_counts()

Loan_Status
Y    271
N    110
Name: count, dtype: int64

In [25]:
df[df.Loan_Status.isna()]

Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Property_Area, Loan_Status]
Index: []